#!/bin/bash

location=$(find /opt/django -name 'settings.py')
User=$(awk -F: "/'USER':/" $location | xargs | cut -d":" -f2 |cut -d ',' -f1)
Ip=$(awk -F: "/'HOST':/" $location | xargs | cut -d":" -f2 | cut -d ',' -f1)
Pass=$(awk -F: "/'PASSWORD':/" $location | cut -d":" -f2 | cut -d "," -f1 | xargs)

Con=$(PGPASSWORD=$Pass psql -h $Ip -U $User -w -c "SELECT 1 FROM pg_roles WHERE rolname='postgres'" 2>/dev/null | awk '/row/' | cut -d "(" -f2 | cut -d ' ' -f1 | xargs) 


if [[ $Con == 1 ]]; then
	
	echo "OK - django server is connected to the postgress server"
	exit 0

elif [ -z "$User" -o -z "$Pass" ]; then 
	
	echo "WARNING - User or Password has been missed"
	exit 1

elif [ -z "$Ip" ]; then
	
	echo "CRITICAL - No connection with the postgres server"
	exit 2

else
	echo "UNKNOWN - something is wrong with the connection"
	exit 3

fi
