#!/bin/bash

loadavg=$( uptime | awk -F: '{print $5}' | xargs)

load1int=$( echo $loadavg | cut -d "." -f 1)
load2int=$( echo $loadavg | awk -F, '{print $2}' | xargs | cut -d "." -f 1)
load3int=$( echo $loadavg | awk -F, '{print $3}' | xargs | cut -d "." -f 1)

load1=$( echo $loadavg | awk -F, '{print $1}')
load2=$( echo $loadavg | awk -F, '{print $2}')
load3=$( echo $loadavg | awk -F, '{print $3}')

output="Load Average: $loadavg | Load_1_min=$load1, Load_5_min=$load2, Load_15_min=$load3"

if [ $load1int -le 1 -a $load2int -le 1 -a $load3int -le 1 ]
then
	echo "OK - $output"
	exit 0

elif [ $load1int -le 2 -a $load2int -le 2 -a $load3int -le 2 ]
then
	echo "WARNING - $output"
	exit 1
elif [ $load1int -gt 2 -a $load2int -gt 2 -a $load3int -gt 2 ]
then
	echo " CRITICAL - $output"
	exit 2
else
	echo "UNKNOWN - $output"
	exit 3
fi
